sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - DEPS=highest
    - PHPCS=false
    - COVERAGE=false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
    - php: 7.0
      env: DEPS=lowest
    - php: 7.1
      env:
        - PHPCS=true 
        - COVERAGE=true
    - php: 7.1
      env: DEPS=lowest
    - php: 7.2
    - php: 7.2
      env: DEPS=lowest

before_install:
  - if [[ "$COVERAGE" != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --no-suggest
  - if [[ "$DEPS" == 'highest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ "$DEPS" == 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - ./vendor/bin/phpunit
  - if [[ "$PHPCS" == 'true' ]]; then ./vendor/bin/phpcs ; fi
  - if [[ "$COVERAGE" == 'true' ]]; then composer test-coverage ; fi

after_script:
  - if [[ "$COVERAGE" == 'true' ]]; then composer upload-coverage ; fi